music_directory "/home/seven/Music"
playlist_directory "/home/seven/Music"
db_file "/home/seven/.config/mpd/database"
log_file "/home/seven/.config/mpd/log"
pid_file "/home/seven/.config/mpd/pid"
state_file "/home/seven/.config/mpd/state"
sticker_file "/home/seven/.config/mpd/sticker.sql"

bind_to_address "127.0.0.1"
bind_to_address "/home/seven/.config/mpd/socket"

audio_output {
    type "pulse"
    name "PulseAudio"
}
